dataset:
  dataset_size: 16
  train_filepath: "train.tsv"
  val_filepath: "test.tsv"
  num_workers: 2
  batch_size: 8
  normalize_spec: true
  f_max: 8000
  n_channels: 1
  target_audio_length: 8192
  sr: 48000
  target_sr: 22050
  n_fft: 1024
  n_mels: 80
  hop_size: 256
  win_si1ze: 1024

rcg:
  top_k: 4
  n_conv_blocks: 5
  num_kernels: 3
  negative_slope: 0.1
  channels: [256, 128, 64, 32, 16]
  kernel_sizes: [3, 7, 11]

fre-gan:
  seed: 7
  epochs: 3
  n_gpus: 1
  val_every_epoch: 1
  optimizer: "AdamW"
  current_device: "cuda"
  save_every_epoch: 1
  lr: 0.0002
  b1: 0.8
  b2: 0.99
  lr_decay: 0.999

wandb:
  progress_bar_refresh_rate: 1
  checkpoint_directory: null
  project: "Mel-Fre-GAN"
  offline: false
  log_every_n_steps: 8
