dataset:
  train_filepath: "train.tsv"
  val_filepath: "test.tsv"
  normalize_spec: True
  f_max: 8000
  train: False
  n_channels: 1
  target_audio_length: 1
  sr: 44100
  n_fft: 1024
  n_mels: 80
  hop_size: 256
  win_si1ze: 1024