dataset:
  speaker_id: "391f19cc56c80b71950a424f9dff058a997032adeb86035391cb71d437f6de3168091c5a7aad0cbd28cc5ae0c66ba67c4e000ce26070c6d3e2810288267220b9"
  dataset_size: null
  filepath: "train.tsv"
  num_workers: 1
  batch_size: 8
  f_min: 0
  f_max: 8000
  n_channels: 1
  target_audio_length: 8192
  train_set_size: 0.8
  sr: 48000
  target_sr: 22050
  n_fft: 1025
  n_mels: 80
  hop_size: 256
  win_size: 1024
  power: 1.0

rcg:
  top_k: 4
  n_conv_blocks: 5
  num_kernels: 3
  negative_slope: 0.1
  channels: [256, 128, 64, 32, 16]
  kernel_sizes: [3, 7, 11]

fre-gan:
  seed: 7
  epochs: 50
  n_gpus: 1
  val_every_epoch: 1
  optimizer: "AdamW"
  current_device: "cuda"
  save_every_epoch: 10
  warm_up_steps: 0
  lr_gen: 0.0005
  lr_dis: 0.0002
  b1: 0.8
  b2: 0.999
  lr_decay: 0.99

wandb:
  save_dir: null
  progress_bar_refresh_rate: 1
  checkpoint_directory: null
  project: "Single-Speaker-Fixed-mels-Warm-up-1k"
  offline: false
  log_every_n_steps: 8
